# agents/signal_collector/detectors/forecast.py
"""
Capacity / latency-forecast detector powered by the Splunk AI Toolkit (MLTK).

Instead of a hand-rolled sigma threshold, this detector asks Splunk to forecast
the expected metric with MLTK's `| predict` and flags points that breach the
upper confidence band. The SPL is generated by `agents.common.splunk_ai.mltk`.
"""
from __future__ import annotations
from datetime import timedelta

from .base import BaseDetector
from ..models import RawSignal, SignalCategory, SignalMagnitude
from agents.common.splunk_ai.mltk import forecast_spl


class CapacityForecastDetector(BaseDetector):
    category = SignalCategory.CAPACITY
    query_file = ""  # SPL is generated via MLTK, not loaded from a file

    # Defaults; a future config could parameterize these.
    index = "prod"
    sourcetype = "checkout-svc"
    metric = "p99(response_ms)"

    def _build_query(self) -> str:
        return forecast_spl(self.index, self.sourcetype, metric=self.metric)

    def _parse_results(self, rows, spl):
        signals = []
        for row in rows:
            if int(row.get("breach", 0)) != 1:
                continue
            ts = self._parse_dt(row["_time"])
            value = float(row["actual"])
            forecast = float(row["forecast_upper"])
            signals.append(RawSignal(
                signal_id=self._new_signal_id(),
                category=self.category,
                service=row.get("service", self.sourcetype),
                started_at=ts,
                ended_at=ts + timedelta(minutes=int(row.get("window_min", 60))),
                magnitude=SignalMagnitude(
                    metric=row.get("metric", self.metric),
                    value=value,
                    baseline=forecast,
                    deviation_sigma=float(row.get("sigma", 0)),
                    unit="ms",
                ),
                splunk_query=spl,
                correlation_ids=["mltk:predict"],
                raw_sample_size=int(row.get("request_count", 0)),
            ))
        return signals
